version: 2
jobs:
  build:
    docker:
    - image: circleci/php
    working_directory: ~/repo
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.05.0-ce
        docker_layer_caching: true
    - run:
        name: Login to DockerHub
        command: docker login -u $DOCKERHUB_LOGIN -p$DOCKERHUB_PASS

    - run:
        name: davidsolc/php:7.3-fpm
        command: |
          docker image build -t davidsolc/php:7.3-fpm ./php/7.3-fpm
          docker image push davidsolc/php:7.3-fpm
    - run:
        name: davidsolc/php:7.3-fpm-production
        command: |
          docker image build -t davidsolc/php:7.3-fpm-production ./php/7.3-fpm-production
          docker image push davidsolc/php:7.3-fpm-production

    - run:
        name: davidsolc/php:7.3-fpm-alpine
        command: |
          docker image build -t davidsolc/php:7.3-fpm-alpine ./php/7.3-fpm-alpine
          docker image push davidsolc/php:7.3-fpm-alpine
    - run:
        name: davidsolc/php:7.3-fpm-alpine-production
        command: |
          docker image build -t davidsolc/php:7.3-fpm-alpine-production ./php/7.3-fpm-alpine-production
          docker image push davidsolc/php:7.3-fpm-alpine-production

workflows:
  version: 2
  workflow:
    jobs:
    - build
